package com.example.library_demo;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Author {

    @Id
    @AutoGenerated
    private Long id;
    private String firstName;
    private String lastName;

    public Author() {
    }
    
    public Author(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

}
